import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { register } from "swiper/element/bundle";
import { Provider } from "react-redux";
import store from "@/store/store";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "KINOPOISK Lite",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	register();
	return (
		<Provider store={store}>
			<html lang="en">
				<body className={inter.className}>{children}</body>
			</html>
		</Provider>
	);
}
